# Enable HTTP
quarkus.http.insecure-requests=enabled
# Setup PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ping
quarkus.transaction-manager.default-transaction-timeout=3000s
quarkus.hibernate-orm.log.queries-slower-than-ms=200
quarkus.hibernate-orm.database.generation=update
# Set port
quarkus.http.port=8080
quarkus.devservices.enabled=true
%test.quarkus.devservices.enabled=false

PROJECT_DEFAULT_PATH=/tmp/ping/projects
LOG_FILE=/tmp/ping/log.txt

smallrye.jwt.new-token.signature-algorithm=RS256
smallrye.jwt.sign.key.location=privateKey.pem

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ping-api

# CORS CONFIG 
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true
